### ISSUE TITLE
Formatação do arquivo de acordo com as normas ABNT

### ISSUE THREAD

**Issue by thaynaracsantos** [rohanaceres/tcc#18]
**Elementos Pré-textuais** 
- [X] Capa 

- [ ] Folha de rosto

- [ ] Folha de aprovação

- [ ] Dedicatória

- [ ] Agradecimentos

- [ ] Resumo

- [ ] Abstract 

**Elementos textuais**

- [x] Introdução 

- [ ] Desenvolvimento

- [ ] Conclusão 

**Elementos Pós-textuais**

- [ ] Referências

- [ ] Anexo 

- [ ] Glossário

**Comment by rohanaceres** [comment]
você pretende fechar essa issue só no final do trabalho?

**Comment by thaynaracsantos** [comment]
Sim, ou você acha melhor ir quebrando ela em várias partes?
