### ISSUE TITLE
Breve resumo histórico e estado da arte

### ISSUE THREAD

**Issue by rohanaceres** [rohanaceres/tcc#2]
# Breve resumo histórico e estado da arte

## Breve resumo histórico

O contexto que originou o problema que o TCC está se propondo a resolver/mitigar.

* Pesquisas de medição da poluição
* Uso de transporte alternativo

## Estado da arte

Tecnologias atuais; contexto atual sendo utilizado para resolver/mitigar o problema proposto.

* 4 parágrafos por _paper_. Pesquisar no google academics e resumir o _abstract_, _introduction_ e _conclusion_ de cada _paper_. Colocar o link de cada um aqui na issue.
    * 3 _papers_ de 2017
    * 2 _papers_ de 2016
    * 1 _paper_ de 2015

⚠️ **Colocar todas as referências dos sites consultados aqui na issue.**

**Comment by thaynaracsantos** [comment]
Papers:

[(October 2017) Urban emissions hotspots: Quantifying vehicle congestion and air pollution using mobile phone GPS data](http://www.sciencedirect.com/science/article/pii/S0269749117304001)
[(September 2017) Effects of air pollution on infant and children respiratory mortality in four large Latin-American cities](http://www.sciencedirect.com/science/article/pii/S0269749117313568)
[(April  2017) Characteristics and applications of small, portable gaseous air pollution monitors](http://www.sciencedirect.com/science/article/pii/S0269749116307321)
[(March 2017) Potential pollution exposure reductions from small-distance bicycle lane separations](https://www.sciencedirect.com/science/article/pii/S2214140516303504)
[(November 2016) Hotspots of black carbon and PM2.5 in an urban area and relationships to traffic characteristics](http://www.sciencedirect.com/science/article/pii/S0269749116305978)
[(November 2016) Effects of moving-vehicle wakes on pollutant dispersion inside a highway road tunnel](http://www.sciencedirect.com/science/article/pii/S0269749116306650)
[(November 2016) Trip Route Planning for Bicycle-Sharing Systems](http://www.ifmlab.org/files/paper/2016_cic_paper.pdf)
[(March 2016) Dynamic assessment of inhaled air pollution using GPS and accelerometer data](https://www.sciencedirect.com/science/article/pii/S2214140515006891)
[(September 2016)A Study of LoRa: Long Range & Low Power
Networks for the Internet of Things](http://www.thomasclausen.net/wp-content/uploads/2016/09/2016-A-Study-of-LoRa-Long-Range-Low-Power-Networks-for-the-Internet-of-Things.pdf)
https://pt.wikipedia.org/wiki/Di%C3%B3xido_de_nitrog%C3%A9nio

**Comment by thaynaracsantos** [comment]
Alternative transport:
http://www.rj.gov.br/web/setrans/exibeconteudo?article-id=839553
https://vestibular.uol.com.br/resumo-das-disciplinas/atualidades/mobilidade-urbana-no-brasil-transporte-publico-tem-pouco-investimento-e-a-preferencia-ainda-e-do-carro.htm
https://noticias.uol.com.br/saude/album/1109_bikesnomundo_album.htm#fotoNav=5
https://ciclofemini.com.br/comportamento/top-ten-paises-amigos-da-bicicleta-por-claudia-franco/
http://www.rj.gov.br/web/setrans/exibeconteudo?article-id=275563
http://www.riodebicicleta.com.br/
http://thecityfixbrasil.com/2012/06/28/paises-com-maiores-indices-de-uso-de-bike-sao-os-mais-seguros-para-ciclistas/
